<?php

namespace IFabrikator\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * ControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlRepository extends EntityRepository
{
    public function getPageControls(Page $page){

        if($page){
            $qb = $this->_em->createQueryBuilder();
            $controls = $qb->select('c')
                ->from('IFabrikatorCoreBundle:Control', 'c')
                ->innerJoin('c.pages', 'p', 'WITH', 'p.id = :pageID')
                ->where('c.isActive = :isActive')
                ->setParameters(array(
                    'isActive'=>true,
                    'pageID'=>$page->getId(),
                ))
                ->getQuery()
                ->getResult();

            return $controls;

        }

        return null;

    }
}
