<?php

namespace IFabrikator\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{

    public function getActivePageByURL($url, Site $site, $language){

        if($site){
            $qb = $this->_em->createQueryBuilder();
            $page = $qb->select('p')
                ->from('IFabrikatorCoreBundle:Page', 'p')
                ->where(
                    $qb->expr()->andX(
                        $qb->expr()->eq('p.url', ':url'),
                        $qb->expr()->eq('p.isActive', ':isActive'),
                        $qb->expr()->eq('p.language', ':language'),
                        $qb->expr()->eq('p.site', ':site')
                    )

                )->setMaxResults(1)
                ->setParameters(array(
                    'url'=>$url,
                    'isActive'=>true,
                    'language'=>$language,
                    'site'=>$site,
                ))
                ->getQuery()
                ->getResult();

                return isset($page[0]) ? $page[0] : null;


        }
        return null;

    }
}
