<?php

namespace IFabrikator\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{

    public function getSiteByHost($host){

        $siteRepository = $this->_em->getRepository('IFabrikatorCoreBundle:Site');

        $site = $siteRepository->findOneByHost($host);

        if(!$site){
            $siteAliasRepository = $this->_em->getRepository('IFabrikatorCoreBundle:SiteAlias');
            $siteAlias = $siteAliasRepository->findOneByHost($host);
            $site = ($siteAlias instanceof SiteAlias) ? $siteAlias->getSite() : null;
        }

        return $site;
    }
}
