<?php

namespace IFabrikator\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiteAliasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteAliasRepository extends EntityRepository
{
}
